kind: pipeline
type: docker
name: calculator

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment: 
      pgconn:
        from_secret: pgconn
    commands: 
      - echo "pgconn=$pgconn" >> api/appsettings.test.json
      - cat api/appsettings.test.json
      - dotnet sonarscanner begin 
        /k:"easv-devops_KT.calculator_AY3gpwBlEVvRW2O60EKq"
        /d:sonar.host.url="http://sonar.setgo.dk:9000"  
        /d:sonar.token="sqp_49c3da203c9b74235f209cb14c5b52bb6d94d1a7"
        /d:sonar.cs.vscoveragexml.reportsPaths=./coverage.xml
        /d:sonar.qualitygate.wait=truerun
      - dotnet build
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="sqp_49c3da203c9b74235f209cb14c5b52bb6d94d1a7"